"""Shared components for Nexus."""

from shared.database import AsyncSessionLocal, get_db, init_db
from shared.models import Base
from shared.redis_client import GroupScopedRedis, get_redis

# Import intelligence models and add to Base metadata
from shared.models_intelligence import (
    BehaviorPattern,
    MemberBehaviorLog,
    PredictiveScore,
    ConversationNode,
    ConversationEdge,
    AnomalyEvent,
    MemberJourney,
    TopicCluster,
    ChurnPrediction,
    AutomationRule,
    BehavioralTripwire,
    MemberTripwireState,
    TimeBasedRuleSet,
    SmartCooldown,
    AutomatedEvent,
    BroadcastCampaign,
    DMCampaign,
    AnnouncementReaction,
    MemberPreferences,
    AdminPreferences,
    GroupTheme,
    CustomRankName,
    CustomEconomyConfig,
    WelcomeFlow,
    CoordinatedAttack,
    HoneypotTrap,
    VerificationLevel,
    VerificationRequirement,
    ShadowWatchSession,
    ShadowWatchMessage,
    WebhookConfig,
    WebhookLog,
    EventSubscription,
    TimeCapsule,
    GroupSoundtrack,
    LegacyMember,
    GroupOath,
    OathAcceptance,
    LiveCollaborationSession,
    SeasonalMode,
)

__all__ = [
    "Base",
    "AsyncSessionLocal",
    "get_db",
    "init_db",
    "GroupScopedRedis",
    "get_redis",
    # Intelligence models
    "BehaviorPattern",
    "MemberBehaviorLog",
    "PredictiveScore",
    "ConversationNode",
    "ConversationEdge",
    "AnomalyEvent",
    "MemberJourney",
    "TopicCluster",
    "ChurnPrediction",
    "AutomationRule",
    "BehavioralTripwire",
    "MemberTripwireState",
    "TimeBasedRuleSet",
    "SmartCooldown",
    "AutomatedEvent",
    "BroadcastCampaign",
    "DMCampaign",
    "AnnouncementReaction",
    "MemberPreferences",
    "AdminPreferences",
    "GroupTheme",
    "CustomRankName",
    "CustomEconomyConfig",
    "WelcomeFlow",
    "CoordinatedAttack",
    "HoneypotTrap",
    "VerificationLevel",
    "VerificationRequirement",
    "ShadowWatchSession",
    "ShadowWatchMessage",
    "WebhookConfig",
    "WebhookLog",
    "EventSubscription",
    "TimeCapsule",
    "GroupSoundtrack",
    "LegacyMember",
    "GroupOath",
    "OathAcceptance",
    "LiveCollaborationSession",
    "SeasonalMode",
]
